from reportlab.lib.pagesizes import A4
from reportlab.pdfgen import canvas
from reportlab.lib.colors import HexColor
from reportlab.platypus import Paragraph, Frame
from reportlab.lib.styles import ParagraphStyle

def create_feedback_pdf(name, score, matched, missing):
    """Generate a modern, neatly formatted feedback PDF."""
    
    fname = f"{name}_feedback.pdf"
    c = canvas.Canvas(fname, pagesize=A4)
    width, height = A4

    # ----------- COLORS -----------
    primary = HexColor("#4B57FF")
    text_color = HexColor("#000000")

    # ----------- TITLE -----------
    c.setFillColor(primary)
    c.setFont("Helvetica-Bold", 22)
    c.drawCentredString(width / 2, height - 70, "SMART ATS FEEDBACK REPORT")

    # ----------- SUBTITLE -----------
    c.setFont("Helvetica", 12)
    c.setFillColor(text_color)
    c.drawCentredString(width / 2, height - 95, "AI-Powered Resume Evaluation Certificate")

    # ----------- SECTION STYLE -----------
    style = ParagraphStyle(
        name="content",
        fontName="Helvetica",
        fontSize=12,
        textColor=text_color,
        leading=15
    )

    # Wrap text for matched & missing
    matched_text = matched if matched else "No strong skills detected."
    missing_text = missing if missing else "No major improvements required."

    content = f"""
    <b>Candidate Name:</b> {name}<br/><br/>
    <b>Overall ATS Match Score:</b> {score}%<br/><br/>

    <b>✔ Strengths Identified:</b><br/>
    {matched_text}<br/><br/>

    <b>⚠ Areas to Improve:</b><br/>
    {missing_text}<br/><br/>

    <b>Final Review:</b><br/>
    {"Strong candidate with excellent skill alignment." if score >= 75 else 
    "Moderate match. Candidate shows potential but needs skill improvements." if score >= 50 else 
    "Not suitable for the current role. Skill gap is significant."}
    <br/><br/>

    <i>This certificate was auto-generated by Smart ATS — an intelligent hiring assistant.</i>
    """

    # ----------- TEXT FRAME (Auto Layout) -----------
    frame = Frame(50, 100, width - 100, height - 180, showBoundary=0)
    frame.addFromList([Paragraph(content, style)], c)

    c.save()
    return fname

